apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-fe
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: fe
        image: nginx
        ports:
        - containerPort: 80
