apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-fe
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: node-fe
        image: quanlh0604/front-end-week-3
        ports:
        - containerPort: 4200
