pipeline {
    agent {
        label "k8s"
    }
    environment{
        LOCATIONS = "/k8s/project-1/"
    }
    stages {
        stage ("Validate") {
            steps {
                sh "docker version"
            }
        }
        stage ("build images back-end") {
            steps {
                sh "cd /k8s/project-1/be"
                sh " ./build-images.sh"
            }
        }
        stage ("Deploy back-end service") {
            steps {
                sh "cd .."
                sh "kubectl apply -f ${LOCATIONS}/deployment-backend.yaml"
            }
        }
    }
    post {
        always {
            echo 'Cleaning up workspace'
            sh "docker rmi  quanlh0604/backend-week-3 || true"
            deleteDir() 
        }
    }
}